/*
 * SPDX-FileCopyrightText: 2026 Sayeh Ava Pazouki
 * SPDX-License-Identifier: GPL-3.0-or-later
 * SPDX-FileComment: Additional terms apply; see ADDITIONAL_TERMS.md.
 */

window.PridgeStrings = Object.freeze({
  status: "Status",
  plugins: "Plugins",
  plugins_hint: "Manage the plugins that extend Pridge Client, grouped by category.",
  plugins_count: "{count} plugins installed",
  servers: "Servers",
  servers_count: "{count} servers configured",
  printers: "Printers",
  printers_count: "{count} printers found",
  printers_hint: "Configure the default printing mode, driver settings, and submission method for each installed printer, independent of any server. Test print here before adding a server.",
  default_printer: "Default",
  settings: "Settings",
  about: "About",
  quit: "Quit",
  server_connections: "Server Connections",
  server_connections_hint: "Configured Pridge servers",
  add_server: "Add Server",
  server_pages: "Server pages",
  previous_page: "Previous page",
  next_page: "Next page",
  page_number: "Page {page}",
  page_summary: "{page} of {pages}",
  edit_server: "Edit Server",
  no_servers: "No servers configured",
  no_servers_hint: "Add a server to start receiving print jobs.",
  enabled: "Enabled",
  disabled: "Disabled",
  token_saved: "Token saved",
  token_missing: "Token missing",
  polling_short: "polling",
  heartbeat_short: "heartbeat",
  mappings_short: "mappings",
  edit: "Edit",
  remove: "Remove",
  printer_selection: "Printer Selection",
  printer: "Printer",
  no_printers: "No printers found",
  no_used_printers: "No printers have been used yet.",
  printer_activity_settings_title: "Printer Activity settings",
  printer_activity_used_only: "Show only printers I've used",
  refresh: "Refresh",
  endpoint_controls: "Endpoint Controls",
  endpoint_controls_hint: "Start or stop all enabled server connections together.",
  start_polling_on_launch: "Start polling on launch",
  start_at_login: "Start at login",
  connection_status: "Connection Status",
  heartbeat: "Heartbeat",
  save: "Save",
  start: "Start",
  stop: "Stop",
  start_all: "Start Enabled",
  stop_all: "Stop All",
  recent_jobs: "Recent Jobs",
  no_jobs: "No jobs yet",
  logs_status: "Logs / Status",
  no_logs: "No log output yet",
  add_widget: "Add Widget",
  drag_to_reorder: "Drag to reorder",
  remove_widget: "Remove widget",
  configure_widget: "Configure widget",
  server_status: "Server Status",
  server_status_none_selected: "No servers selected",
  server_status_none_selected_hint: "Choose which servers to track using the gear icon above.",
  server_status_settings_title: "Server Status settings",
  server_status_pick_servers: "Servers to track",
  server_status_auto_rotate: "Auto-rotate through tracked servers",
  server_status_heartbeat: "Last heartbeat",
  server_status_no_heartbeat: "No heartbeat yet",
  server_status_polling_every: "Polling every {seconds}s",
  loading: "Loading Pridge Client…",
  confirm_remove: "Remove {name}? This also removes its stored client token.",
  remove_server_title: "Remove server?",
  server_name: "Server Name",
  server_url: "Server URL",
  client_token: "Client Token",
  client_token_hint: "Stored tokens remain hidden. Leave this empty to keep the existing token.",
  token_saved_placeholder: "Token saved (hidden)",
  token_missing_placeholder: "Enter client token",
  show_token: "Show token",
  polling_interval: "Polling Interval",
  heartbeat_interval: "Heartbeat Interval",
  seconds: "seconds",
  test_connection: "Test Connection",
  testing: "Testing…",
  cancel: "Cancel",
  add: "Add Server",
  update: "Save Changes",
  server_required: "Server name and URL are required.",
  server_not_found: "Server not found.",
  save_failed: "Could not save server settings.",
  connection_success: "Connection successful.",
  connection_failed: "Connection failed.",
  printer_mappings: "Remote Printer Mappings",
  printer_mappings_hint: "Every server endpoint is listed automatically. Choose Disabled or a local printer for each endpoint.",
  discovering: "Discovering…",
  refresh_endpoints: "Refresh Endpoints",
  no_mappings: "No virtual printer endpoints are available on this server.",
  local_printer: "Local Printer",
  local_printers: "Local Printers",
  configure: "Configure",
  printer_setup: "Printer Setup",
  printing_mode: "Printing Mode",
  raw_mode: "RAW data",
  system_driver_mode: "System driver",
  raw_mode_hint: "Sends the original printer-ready bytes without changing encoding, line endings, or binary data.",
  system_driver_mode_hint: "Submits the document through the operating system and the installed printer driver.",
  system_driver_unavailable: "No installed system driver is available for this printer.",
  loading_driver_capabilities: "Reading options from the installed printer driver…",
  driver_capabilities_failed: "Could not read the installed printer driver's options.",
  printer_profile_save_failed: "Could not save this printer's settings.",
  done: "Done",
  working: "Working…",
  test_print: "Test Print",
  remote_prints: "Remote",
  test_print_driver_only: "Test Print is available in System Driver mode.",
  test_print_failed: "Could not submit the test page.",
  test_print_submitted: "Test page submitted to the printer.",
  native_driver_settings: "Installed driver preferences",
  native_driver_settings_hint: "The printer driver controls and saves the settings shown in its native window.",
  open_driver_settings: "Open Driver Settings",
  native_driver_settings_failed: "Could not open the installed printer driver's settings.",
  driver_settings_updated: "Driver settings updated.",
  no_driver_options: "The installed driver did not report any configurable job options.",
  submission_method: "Submission Method",
  submission_method_automatic: "Automatic (recommended)",
  submission_method_direct_pdf: "CUPS direct",
  submission_method_pdfium: "Render with PDFium",
  submission_method_hint: "CUPS direct hands the PDF straight to the printer's own driver. Rendering with PDFium first can help with printers that reject certain PDFs.",
  fit_mode: "Page Fit",
  fit_mode_fit: "Fit to page",
  fit_mode_actual_size: "Actual size",
  fit_mode_hint: "Fit to page scales the document to match this printer's selected paper size. Actual size prints 1:1 with no scaling — use this for continuous-roll or label printers where the document is already sized to match.",
  mapping_disabled: "Disabled",
  server_endpoint_disabled: "Disabled on server",
  no_remote_printers: "No virtual printer endpoints are available on this server.",
  remote_printers_found: "Found {count} remote printer(s).",
  automatic_server_hint: "Include this server when starting enabled servers and on application launch.",
  appearance: "Appearance",
  appearance_hint: "Choose how light or dark the Pridge workspace should feel.",
  darkness_amount: "Window darkness",
  darkness_grades: [
    { name: "Quartz", tone: "Lightest" },
    { name: "Moonstone", tone: "Soft" },
    { name: "Labradorite", tone: "Balanced" },
    { name: "Onyx", tone: "Deep" },
    { name: "Obsidian", tone: "Darker" },
    { name: "Jet", tone: "Darkest" },
  ],
  startup: "Startup",
  settings_saved: "Settings saved.",
  saving_settings: "Saving…",
  settings_saved_automatically: "Saved automatically.",
  diagnostics: "Diagnostics",
  log_file_enabled: "Automatically save logs to file",
  log_file_enabled_hint: "Keeps a rolling log file on disk so you can export it later. This is independent of the Logs widget on the dashboard, which always shows recent activity.",
  log_retention_days: "Keep logs for",
  days: "days",
  log_directory: "Log file location",
  log_directory_default: "Default location",
  choose_folder: "Choose Folder",
  choosing_folder: "Choosing…",
  reset_to_default: "Reset to Default",
  log_directory_failed: "Could not open the folder picker.",
  clear: "Clear",
  clear_logs: "Clear Logs",
  clear_logs_hint: "Delete all saved log files. The next export will only include new activity.",
  clear_logs_confirm_title: "Clear all logs?",
  clear_logs_confirm_message: "This permanently deletes all saved log files. This cannot be undone.",
  clearing_logs: "Clearing…",
  logs_cleared: "Logs cleared.",
  no_logs_to_clear: "There are no saved logs to clear.",
  export_log: "Export Run Log",
  export_log_hint: "Save saved log entries for troubleshooting or support.",
  export_log_range_from: "From",
  export_log_range_to: "To",
  export_log_range_hint: "Leave both empty to export everything currently saved.",
  exporting_log: "Exporting…",
  log_exported: "Run log exported.",
  log_export_failed: "Could not export the run log.",
  no_log_file: "No log file was found to export yet.",
  no_log_entries_in_range: "No log entries were found in that date range.",
  no_plugins: "No plugins are registered.",
  no_plugins_match_filter: "No plugins match this filter.",
  plugins_all_tab: "All Plugins",
  plugin_category_unknown: "Uncategorized",
  plugin_filter_all: "All",
  plugin_filter_active: "Active",
  plugin_filter_inactive: "Inactive",
  plugin_core: "Core",
  renderer_third_party: "Third-party",
  renderer_load_error: "Failed to load",
  plugin_settings: "Settings",
  install_plugin: "Install Plugin…",
  install_plugin_hint: "Select a plugin folder containing manifest.json to install a third-party renderer.",
  installing_plugin: "Installing…",
  plugin_installed: "Plugin installed.",
  plugin_install_failed: "Could not install the plugin.",
  plugin_remove_confirm: "Remove the plugin \"{name}\"?",
  plugin_removed: "Plugin removed.",
  plugin_remove_failed: "Could not remove the plugin.",
  rescan_plugins: "Rescan Plugins",
  rescanning_plugins: "Rescanning…",
  plugins_rescanned: "Plugins rescanned.",
  app_mappings: "External Application Mappings",
  mappings_count: "{count} mappings configured",
  app_mappings_hint: "Map file types to installed applications that convert them to PDF.",
  no_app_mappings: "No application mappings configured.",
  add_mapping: "Add Mapping",
  mapping_name: "Name",
  mapping_extensions: "File Extensions",
  mapping_extensions_hint: ".psd, .ai, .docx",
  mapping_mime_types: "MIME Types",
  mapping_mime_types_hint: "image/vnd.adobe.photoshop (optional)",
  mapping_executable: "Executable Path",
  mapping_arguments: "Arguments",
  mapping_arguments_hint: "One per line. Use {input} for the source file and {output} for the output PDF.",
  mapping_timeout: "Timeout (seconds)",
  mapping_platform: "Platform",
  mapping_platform_all: "All platforms",
  mapping_platform_windows: "Windows only",
  mapping_platform_macos: "macOS only",
  mapping_platform_linux: "Linux only",
  mapping_save: "Save Mapping",
  mapping_cancel: "Cancel",
  mapping_remove_confirm: "Remove mapping \"{name}\"?",
  close: "Close",
  about_title: "Pridge Client",
  about_description: "A secure desktop bridge that connects Pridge servers to local printers, receives print jobs, and sends their original data safely to the selected printer.",
  original_author: "Original author",
  version: "Version",
  build_variant: "Build variant",
  build_system: "Build system",
  copyright: "Copyright",
  copyright_value: "© 2026 Sayeh Ava Pazouki",
  license: "License",
  license_value: "GPL-3.0-or-later",
  additional_terms_notice: "Modified or redistributed versions must keep this attribution visible under GNU GPLv3 Section 7(b).",
});
