/*
 * SPDX-FileCopyrightText: 2026 Sayeh Ava Pazouki
 * SPDX-License-Identifier: GPL-3.0-or-later
 * SPDX-FileComment: Additional terms apply; see ADDITIONAL_TERMS.md.
 */

window.PridgeStrings = Object.freeze({
  status: "Status",
  plugins: "Plugins",
  plugins_hint: "Manage the plugins that extend Pridge Client, grouped by category.",
  plugins_count: "{count} plugins installed",
  servers: "Servers",
  servers_count: "{count} servers configured",
  printers: "Printers",
  printers_count: "{count} printers found",
  printers_hint: "Configure the default printing mode, driver settings, and submission method for each installed printer, independent of any server. Test print here before adding a server.",
  default_printer: "Default",
  settings: "Settings",
  about: "About",
  quit: "Quit",
  server_connections: "Server Connections",
  server_connections_hint: "Configured Pridge servers",
  add_server: "Add Server",
  server_pages: "Server pages",
  previous_page: "Previous page",
  next_page: "Next page",
  page_number: "Page {page}",
  page_summary: "{page} of {pages}",
  edit_server: "Edit Server",
  no_servers: "No servers configured",
  no_servers_hint: "Add a server to start receiving print jobs.",
  enabled: "Enabled",
  disabled: "Disabled",
  token_saved: "Token saved",
  token_missing: "Token missing",
  polling_short: "polling",
  heartbeat_short: "heartbeat",
  mappings_short: "mappings",
  edit: "Edit",
  remove: "Remove",
  printer_selection: "Printer Selection",
  printer: "Printer",
  no_printers: "No printers found",
  no_used_printers: "No printers have been used yet.",
  printer_activity_settings_title: "Printer Activity settings",
  printer_activity_used_only: "Show only printers I've used",
  refresh: "Refresh",
  endpoint_controls: "Endpoint Controls",
  endpoint_controls_hint: "Start or stop all enabled server connections together.",
  start_polling_on_launch: "Start polling on launch",
  start_at_login: "Start at login",
  connection_status: "Connection Status",
  heartbeat: "Heartbeat",
  save: "Save",
  start: "Start",
  stop: "Stop",
  start_all: "Start Enabled",
  stop_all: "Stop All",
  recent_jobs: "Recent Jobs",
  no_jobs: "No jobs yet",
  logs_status: "Logs / Status",
  no_logs: "No log output yet",
  add_widget: "Add Widget",
  drag_to_reorder: "Drag to reorder",
  drop_at_end: "Drop here to move to the end",
  remove_widget: "Remove widget",
  configure_widget: "Configure widget",
  server_status: "Server Status",
  server_status_none_selected: "No servers selected",
  server_status_none_selected_hint: "Choose which servers to track using the gear icon above.",
  server_status_settings_title: "Server Status settings",
  server_status_pick_servers: "Servers to track",
  server_status_auto_rotate: "Auto-rotate through tracked servers",
  server_status_heartbeat: "Last heartbeat",
  server_status_no_heartbeat: "No heartbeat yet",
  server_status_polling_every: "Polling every {seconds}s",
  loading: "Loading Pridge Client…",
  confirm_remove: "Remove {name}? This also removes its stored client token.",
  remove_server_title: "Remove server?",
  server_name: "Server Name",
  server_url: "Server URL",
  client_token: "Client Token",
  client_token_hint: "Stored tokens remain hidden. Leave this empty to keep the existing token.",
  token_saved_placeholder: "Token saved (hidden)",
  token_missing_placeholder: "Enter client token",
  show_token: "Show token",
  polling_interval: "Polling Interval",
  heartbeat_interval: "Heartbeat Interval",
  seconds: "seconds",
  test_connection: "Test Connection",
  testing: "Testing…",
  cancel: "Cancel",
  add: "Add Server",
  update: "Save Changes",
  server_required: "Server name and URL are required.",
  server_not_found: "Server not found.",
  save_failed: "Could not save server settings.",
  connection_success: "Connection successful.",
  connection_failed: "Connection failed.",
  printer_mappings: "Remote Printer Mappings",
  printer_mappings_hint: "Every server endpoint is listed automatically. Choose Disabled or a local printer for each endpoint.",
  discovering: "Discovering…",
  refresh_endpoints: "Refresh Endpoints",
  no_mappings: "No virtual printer endpoints are available on this server.",
  local_printer: "Local Printer",
  local_printers: "Local Printers",
  configure: "Configure",
  printer_setup: "Printer Setup",
  printing_mode: "Printing Mode",
  raw_mode: "RAW data",
  system_driver_mode: "System driver",
  raw_mode_hint: "Sends the original printer-ready bytes without changing encoding, line endings, or binary data.",
  raw_header_label: "Header (sent before the job)",
  raw_footer_label: "Footer (sent after the job)",
  receipt_template_not_set: "Not set",
  open_receipt_composer: "Edit in Receipt Composer…",
  system_driver_mode_hint: "Submits the document through the operating system and the installed printer driver.",
  system_driver_unavailable: "No installed system driver is available for this printer.",
  loading_driver_capabilities: "Reading options from the installed printer driver…",
  driver_capabilities_failed: "Could not read the installed printer driver's options.",
  printer_profile_save_failed: "Could not save this printer's settings.",
  done: "Done",
  working: "Working…",
  test_print: "Test Print",
  remote_prints: "Remote",
  test_print_driver_only: "Test Print is available in System Driver or RAW mode.",
  test_print_failed: "Could not submit the test page.",
  test_print_submitted: "Test page submitted to the printer.",
  native_driver_settings: "Installed driver preferences",
  native_driver_settings_hint: "The printer driver controls and saves the settings shown in its native window.",
  open_driver_settings: "Open Driver Settings",
  native_driver_settings_failed: "Could not open the installed printer driver's settings.",
  driver_settings_updated: "Driver settings updated.",
  no_driver_options: "The installed driver did not report any configurable job options.",
  submission_method: "Submission Method",
  submission_method_automatic: "Automatic (recommended)",
  submission_method_direct_pdf: "CUPS direct",
  submission_method_pdfium: "Render with PDFium",
  submission_method_hint: "CUPS direct hands the PDF straight to the printer's own driver. Rendering with PDFium first can help with printers that reject certain PDFs.",
  fit_mode: "Page Fit",
  fit_mode_fit: "Fit to page",
  fit_mode_actual_size: "Actual size",
  fit_mode_hint: "Fit to page scales the document to match this printer's selected paper size. Actual size prints 1:1 with no scaling — use this for continuous-roll or label printers where the document is already sized to match.",
  mapping_disabled: "Disabled",
  server_endpoint_disabled: "Disabled on server",
  no_remote_printers: "No virtual printer endpoints are available on this server.",
  remote_printers_found: "Found {count} remote printer(s).",
  automatic_server_hint: "Include this server when starting enabled servers and on application launch.",
  appearance: "Appearance",
  appearance_hint: "Choose how light or dark the Pridge workspace should feel.",
  darkness_amount: "Window darkness",
  darkness_grades: [
    { name: "Quartz", tone: "Lightest" },
    { name: "Moonstone", tone: "Soft" },
    { name: "Labradorite", tone: "Balanced" },
    { name: "Onyx", tone: "Deep" },
    { name: "Obsidian", tone: "Darker" },
    { name: "Jet", tone: "Darkest" },
  ],
  startup: "Startup",
  settings_saved: "Settings saved.",
  saving_settings: "Saving…",
  settings_saved_automatically: "Saved automatically.",
  diagnostics: "Diagnostics",
  log_file_enabled: "Automatically save logs to file",
  log_file_enabled_hint: "Keeps a rolling log file on disk so you can export it later. This is independent of the Logs widget on the dashboard, which always shows recent activity.",
  log_retention_days: "Keep logs for",
  days: "days",
  log_directory: "Log file location",
  log_directory_default: "Default location",
  choose_folder: "Choose Folder",
  choosing_folder: "Choosing…",
  reset_to_default: "Reset to Default",
  log_directory_failed: "Could not open the folder picker.",
  clear: "Clear",
  clear_logs: "Clear Logs",
  clear_logs_hint: "Delete all saved log files. The next export will only include new activity.",
  clear_logs_confirm_title: "Clear all logs?",
  clear_logs_confirm_message: "This permanently deletes all saved log files. This cannot be undone.",
  clearing_logs: "Clearing…",
  logs_cleared: "Logs cleared.",
  no_logs_to_clear: "There are no saved logs to clear.",
  export_log: "Export Run Log",
  export_log_hint: "Save saved log entries for troubleshooting or support.",
  export_log_range_from: "From",
  export_log_range_to: "To",
  export_log_range_hint: "Leave both empty to export everything currently saved.",
  exporting_log: "Exporting…",
  log_exported: "Run log exported.",
  log_export_failed: "Could not export the run log.",
  no_log_file: "No log file was found to export yet.",
  no_log_entries_in_range: "No log entries were found in that date range.",
  no_plugins: "No plugins are registered.",
  no_plugins_match_filter: "No plugins match this filter.",
  plugins_all_tab: "All Plugins",
  plugin_category_unknown: "Uncategorized",
  plugin_filter_all: "All",
  plugin_filter_active: "Active",
  plugin_filter_inactive: "Inactive",
  plugin_core: "Core",
  renderer_third_party: "Third-party",
  renderer_load_error: "Failed to load",
  plugin_settings: "Settings",
  install_plugin: "Install Plugin…",
  install_plugin_hint: "Select a plugin folder containing manifest.json to install a third-party renderer.",
  installing_plugin: "Installing…",
  plugin_installed: "Plugin installed.",
  plugin_install_failed: "Could not install the plugin.",
  plugin_remove_confirm: "Remove the plugin \"{name}\"?",
  plugin_removed: "Plugin removed.",
  plugin_remove_failed: "Could not remove the plugin.",
  rescan_plugins: "Rescan Plugins",
  rescanning_plugins: "Rescanning…",
  plugins_rescanned: "Plugins rescanned.",
  app_mappings: "External Application Mappings",
  mappings_count: "{count} mappings configured",
  app_mappings_hint: "Map file types to installed applications that convert them to PDF.",
  no_app_mappings: "No application mappings configured.",
  add_mapping: "Add Mapping",
  mapping_name: "Name",
  mapping_extensions: "File Extensions",
  mapping_extensions_hint: ".psd, .ai, .docx",
  mapping_mime_types: "MIME Types",
  mapping_mime_types_hint: "image/vnd.adobe.photoshop (optional)",
  mapping_executable: "Executable Path",
  mapping_arguments: "Arguments",
  mapping_arguments_hint: "One per line. Use {input} for the source file and {output} for the output PDF.",
  mapping_timeout: "Timeout (seconds)",
  mapping_platform: "Platform",
  mapping_platform_all: "All platforms",
  mapping_platform_windows: "Windows only",
  mapping_platform_macos: "macOS only",
  mapping_platform_linux: "Linux only",
  mapping_save: "Save Mapping",
  mapping_cancel: "Cancel",
  mapping_remove_confirm: "Remove mapping \"{name}\"?",
  close: "Close",
  about_title: "Pridge Client",
  about_description: "A secure desktop bridge that connects Pridge servers to local printers, receives print jobs, and sends their original data safely to the selected printer.",
  original_author: "Original author",
  version: "Version",
  build_variant: "Build variant",
  build_system: "Build system",
  copyright: "Copyright",
  copyright_value: "© 2026 Sayeh Ava Pazouki",
  license: "License",
  license_value: "GPL-3.0-or-later",
  additional_terms_notice: "Modified or redistributed versions must keep this attribution visible under GNU GPLv3 Section 7(b).",
  receipt_composer: "Receipt Composer",
  receipt_composer_hint: "Design a RAW header and footer for each printer: a logo, decoration shortcodes, and dynamic content like the date or a print counter.",
  receipt_composer_select_printer: "Printer",
  receipt_composer_no_printers: "No printers found. Add one from the Printers window first.",
  receipt_paper_width: "Paper Width (dots)",
  receipt_paper_width_custom: "Custom width…",
  receipt_chars_per_line: "Characters per Line",
  receipt_header: "Header",
  receipt_footer: "Footer",
  receipt_add_block: "Add",
  receipt_remove_block: "Remove",
  receipt_block_text: "Text",
  receipt_block_image: "Image",
  receipt_block_align: "Align",
  receipt_block_bold: "Bold Toggle",
  receipt_block_italic: "Italic Toggle",
  receipt_block_hr: "Horizontal Line",
  receipt_block_blank: "Blank Line",
  receipt_block_newline: "Line Break",
  receipt_block_date: "Date",
  receipt_date_format_custom: "Custom format…",
  receipt_block_print_number: "Print Number",
  receipt_block_counter: "Named Counter",
  receipt_block_random: "Random Number",
  receipt_block_cut: "Cut Paper",
  receipt_block_drawer: "Open Cash Drawer",
  receipt_block_feed: "Feed Lines",
  receipt_block_hex: "Raw Hex Bytes",
  receipt_block_dec: "Raw Decimal Bytes",
  receipt_block_raw: "Unrecognized tag",
  receipt_align_left: "Left",
  receipt_align_center: "Center",
  receipt_align_right: "Right",
  receipt_bold_on: "Start",
  receipt_bold_off: "End",
  receipt_italic_on: "Start",
  receipt_italic_off: "End",
  receipt_italic_hint: "Most printers have no italic RAW command; this shows in the preview only.",
  receipt_cut_full: "Full",
  receipt_cut_partial: "Partial",
  receipt_no_blocks: "No blocks yet. Add one below.",
  receipt_drop_at_end: "Drop here to move to the end",
  receipt_preview: "Preview",
  receipt_view_blocks: "Blocks",
  receipt_view_text: "Plain Text",
  receipt_text_edit_hint: "Edits the same shortcode template the block editor produces — useful for quick tweaks, or if you're scripting this from the CLI later.",
  receipt_images: "Uploaded Images",
  receipt_images_hint: "Upload a monochrome logo or artwork, then reference it from a header or footer as an Image block.",
  receipt_upload_image: "Upload Image…",
  receipt_uploading_image: "Uploading…",
  receipt_no_images: "No images uploaded yet.",
  receipt_remove_image_confirm: "Remove image \"{name}\"? Any block referencing it will stop printing an image.",
  receipt_image_add_failed: "Could not add this image.",
  receipt_counters: "Print Counters",
  receipt_counters_hint: "Every printer has a default print counter. Add named counters for separate sequences (e.g. per receipt type).",
  receipt_default_counter_label: "Print Number (default)",
  receipt_add_counter: "Add Named Counter",
  receipt_counter_name: "Counter key (e.g. vip)",
  receipt_counter_label_placeholder: "Label (optional)",
  receipt_counter_add_failed: "Could not add this counter.",
  receipt_reset: "Reset…",
  receipt_reset_counter_prompt: "New value for \"{name}\":",
  receipt_remove_counter_confirm: "Remove counter \"{name}\"?",
  receipt_select_printer_first: "Select a printer above to edit its receipt header and footer.",
  receipt_test_print: "Test Print",
  receipt_test_print_raw_only: "Test Print here requires RAW mode - switch this printer's mode in the Printers window to use it.",
  receipt_guide_title: "Shortcode Reference",
  receipt_guide_intro: "Every header/footer is built from these shortcodes — the block editor above just writes this same syntax for you. Unknown or mistyped tags never print as literal text; they're silently skipped instead.",
  receipt_guide_category_text: "Text & Layout",
  receipt_guide_category_dynamic: "Dynamic Content",
  receipt_guide_category_images: "Images",
  receipt_guide_category_commands: "Printer Commands",
  receipt_guide_align_desc: "Sets alignment for everything printed after it, until changed again.",
  receipt_guide_bold_desc: "Bolds the text between the two tags.",
  receipt_guide_italic_desc: "Shown in the preview only — most receipt printers have no italic command, so it prints as normal text.",
  receipt_guide_hr_desc: "A dashed line the width of Characters per Line.",
  receipt_guide_blank_desc: "A blank line.",
  receipt_guide_newline_desc: "A line break.",
  receipt_guide_date_desc: "Today's date, as YYYY-MM-DD.",
  receipt_guide_date_format_desc: "Date and/or time in a custom format. Pick a common one from the Date block's dropdown, or type any strftime code (%Y %m %d %H %M %S %p …).",
  receipt_guide_random_desc: "A random number — 6 digits by default, or N digits (1-12).",
  receipt_guide_print_number_desc: "The printer's built-in running counter. Increases by 1 on every real print.",
  receipt_guide_counter_desc: "A named counter you define under Print Counters below, tracked separately from the default one. Increases by 1 on every real print.",
  receipt_guide_image_desc: "Prints an uploaded image as a monochrome bitmap. Upload it under Uploaded Images below, then pick it from an Image block.",
  receipt_guide_cut_desc: "Cuts the paper.",
  receipt_guide_drawer_desc: "Opens the cash drawer, on printers wired for it.",
  receipt_guide_feed_desc: "Feeds N blank lines — 4 by default.",
  receipt_guide_hex_desc: "Sends raw bytes given in hexadecimal — an escape hatch for any command not covered above.",
  receipt_guide_dec_desc: "Sends raw bytes given in decimal — the same escape hatch as [hex:...], for printer manuals that list decimal byte values instead.",
});
