# SPDX-FileCopyrightText: 2026 Sayeh Ava Pazouki
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileComment: Additional terms apply; see ADDITIONAL_TERMS.md.

APP_NAME = "PrintBridge Client"
WINDOW_TITLE = "PrintBridge Client"
WINDOW_ADD_SERVER = "Add Server"
WINDOW_EDIT_SERVER = "Edit Server"
WINDOW_SETTINGS = "Settings"
WINDOW_ABOUT = "About PrintBridge Client"
STATUS_STOPPED = "Stopped"
STATUS_RUNNING = "Running"
STATUS_AUTHENTICATED = "Authenticated"
STATUS_DISCONNECTED = "Disconnected"
MESSAGE_SETTINGS_SAVED = "Settings saved"
MESSAGE_SERVER_REQUIRED = "Server name and URL are required."
MESSAGE_SERVER_NOT_FOUND = "Server not found."
MESSAGE_TOKEN_REQUIRED = "A client token is required to test the connection."
MESSAGE_CONNECTION_SUCCESS = "Connection successful."
MESSAGE_CONNECTION_FAILED = "Could not reach the server. Check the URL and network connection."
MESSAGE_TOKEN_NOT_DISPLAYED = "Stored token is hidden. Enter a new token only when replacing it."
MESSAGE_NO_PRINTERS = "No printers found"
MESSAGE_WINDOW_MINIMIZED = "Window minimized. PrintBridge Client keeps running."
MESSAGE_WINDOW_HIDDEN = "Window hidden. PrintBridge Client keeps running from the tray."
MESSAGE_TRAY_UNAVAILABLE = "Tray support requires installing the tray optional dependencies."
MESSAGE_READY = "Ready"
