window.PrintBridgeStrings = Object.freeze({
  status: "Status",
  quit: "Quit",
  server_connections: "Server Connections",
  server_connections_hint: "Configured PrintBridge servers",
  add_server: "Add Server",
  edit_server: "Edit Server",
  no_servers: "No servers configured",
  no_servers_hint: "Add a server to start receiving print jobs.",
  enabled: "Enabled",
  disabled: "Disabled",
  token_saved: "Token saved",
  token_missing: "Token missing",
  polling_short: "polling",
  heartbeat_short: "heartbeat",
  mappings_short: "mappings",
  fallback_short: "fallback",
  edit: "Edit",
  remove: "Remove",
  printer_selection: "Printer Selection",
  printer: "Printer",
  no_printers: "No printers found",
  refresh: "Refresh",
  endpoint_controls: "Endpoint Controls",
  start_polling_on_launch: "Start polling on launch",
  start_at_login: "Start at login",
  connection_status: "Connection Status",
  heartbeat: "Heartbeat",
  save: "Save",
  start: "Start",
  stop: "Stop",
  start_all: "Start Enabled",
  stop_all: "Stop All",
  recent_jobs: "Recent Jobs",
  no_jobs: "No jobs yet",
  logs_status: "Logs / Status",
  no_logs: "No log output yet",
  loading: "Loading PrintBridge Endpoint…",
  confirm_remove: "Remove {name}? This also removes its stored client token.",
  server_name: "Server Name",
  server_url: "Server URL",
  client_token: "Client Token",
  client_token_hint: "Stored tokens remain hidden. Leave this empty to keep the existing token.",
  token_saved_placeholder: "Token saved (hidden)",
  token_missing_placeholder: "Enter client token",
  show_token: "Show token",
  polling_interval: "Polling Interval",
  heartbeat_interval: "Heartbeat Interval",
  seconds: "seconds",
  test_connection: "Test Connection",
  testing: "Testing…",
  cancel: "Cancel",
  add: "Add Server",
  update: "Save Changes",
  server_required: "Server name and URL are required.",
  server_not_found: "Server not found.",
  save_failed: "Could not save server settings.",
  connection_success: "Connection successful.",
  connection_failed: "Connection failed.",
  printer_mappings: "Remote Printer Mappings",
  printer_mappings_hint: "Map each remote server endpoint to a printer installed on this computer.",
  default_printer: "Fallback Local Printer",
  no_default_printer: "No fallback printer",
  default_printer_hint: "Used only when a remote endpoint has no explicit mapping.",
  discover_remote: "Discover Remote Printers",
  discovering: "Discovering…",
  add_mapping: "Add Mapping",
  no_mappings: "No printer mappings yet.",
  remote_printer_id: "Remote ID",
  remote_printer_name: "Remote Printer",
  local_printer: "Local Printer",
  select_local_printer: "Select local printer",
  remove_mapping: "Remove mapping",
  no_remote_printers: "No active remote queues were found. You can enter an endpoint ID manually.",
  remote_printers_found: "Found {count} remote printer(s).",
  automatic_server_hint: "Include this server when starting enabled servers and on application launch.",
  mapping_required: "Every printer mapping needs a remote ID and a local printer.",
});
