/*
 * SPDX-FileCopyrightText: 2026 Sayeh Ava Pazouki
 * SPDX-License-Identifier: GPL-3.0-or-later
 * SPDX-FileComment: Additional terms apply; see ADDITIONAL_TERMS.md.
 */

window.PrintBridgeStrings = Object.freeze({
  status: "Status",
  settings: "Settings",
  about: "About",
  quit: "Quit",
  server_connections: "Server Connections",
  server_connections_hint: "Configured PrintBridge servers",
  add_server: "Add Server",
  server_pages: "Server pages",
  previous_page: "Previous page",
  next_page: "Next page",
  page_number: "Page {page}",
  page_summary: "{page} of {pages}",
  edit_server: "Edit Server",
  no_servers: "No servers configured",
  no_servers_hint: "Add a server to start receiving print jobs.",
  enabled: "Enabled",
  disabled: "Disabled",
  token_saved: "Token saved",
  token_missing: "Token missing",
  polling_short: "polling",
  heartbeat_short: "heartbeat",
  mappings_short: "mappings",
  edit: "Edit",
  remove: "Remove",
  printer_selection: "Printer Selection",
  printer: "Printer",
  no_printers: "No printers found",
  refresh: "Refresh",
  endpoint_controls: "Endpoint Controls",
  endpoint_controls_hint: "Start or stop all enabled server connections together.",
  start_polling_on_launch: "Start polling on launch",
  start_at_login: "Start at login",
  connection_status: "Connection Status",
  heartbeat: "Heartbeat",
  save: "Save",
  start: "Start",
  stop: "Stop",
  start_all: "Start Enabled",
  stop_all: "Stop All",
  recent_jobs: "Recent Jobs",
  no_jobs: "No jobs yet",
  logs_status: "Logs / Status",
  no_logs: "No log output yet",
  loading: "Loading PrintBridge Client…",
  confirm_remove: "Remove {name}? This also removes its stored client token.",
  remove_server_title: "Remove server?",
  server_name: "Server Name",
  server_url: "Server URL",
  client_token: "Client Token",
  client_token_hint: "Stored tokens remain hidden. Leave this empty to keep the existing token.",
  token_saved_placeholder: "Token saved (hidden)",
  token_missing_placeholder: "Enter client token",
  show_token: "Show token",
  polling_interval: "Polling Interval",
  heartbeat_interval: "Heartbeat Interval",
  seconds: "seconds",
  test_connection: "Test Connection",
  testing: "Testing…",
  cancel: "Cancel",
  add: "Add Server",
  update: "Save Changes",
  server_required: "Server name and URL are required.",
  server_not_found: "Server not found.",
  save_failed: "Could not save server settings.",
  connection_success: "Connection successful.",
  connection_failed: "Connection failed.",
  printer_mappings: "Remote Printer Mappings",
  printer_mappings_hint: "Every server endpoint is listed automatically. Choose Disabled or a local printer for each endpoint.",
  discovering: "Discovering…",
  refresh_endpoints: "Refresh Endpoints",
  no_mappings: "No virtual printer endpoints are available on this server.",
  local_printer: "Local Printer",
  local_printers: "Local Printers",
  mapping_disabled: "Disabled",
  server_endpoint_disabled: "Disabled on server",
  no_remote_printers: "No virtual printer endpoints are available on this server.",
  remote_printers_found: "Found {count} remote printer(s).",
  automatic_server_hint: "Include this server when starting enabled servers and on application launch.",
  appearance: "Appearance",
  appearance_hint: "Choose how light or dark the PrintBridge workspace should feel.",
  darkness_amount: "Window darkness",
  darkness_grades: [
    { name: "Quartz", tone: "Lightest" },
    { name: "Moonstone", tone: "Soft" },
    { name: "Labradorite", tone: "Balanced" },
    { name: "Onyx", tone: "Deep" },
    { name: "Obsidian", tone: "Darker" },
    { name: "Jet", tone: "Darkest" },
  ],
  startup: "Startup",
  settings_saved: "Settings saved.",
  saving_settings: "Saving…",
  settings_saved_automatically: "Saved automatically.",
  close: "Close",
  about_title: "PrintBridge Client",
  about_description: "A secure desktop bridge that connects PrintBridge servers to local printers, receives print jobs, and sends their original data safely to the selected printer.",
  original_author: "Original author",
  version: "Version",
  copyright: "Copyright",
  copyright_value: "© 2026 Sayeh Ava Pazouki",
  license: "License",
  license_value: "GPL-3.0-or-later",
  additional_terms_notice: "Modified or redistributed versions must keep this attribution visible under GNU GPLv3 Section 7(b).",
});
