window.PrintBridgeStrings = Object.freeze({
  status: "Status",
  quit: "Quit",
  server_connections: "Server Connections",
  server_connections_hint: "Configured PrintBridge servers",
  add_server: "Add Server",
  edit_server: "Edit Server",
  no_servers: "No servers configured",
  no_servers_hint: "Add a server to start receiving print jobs.",
  enabled: "Enabled",
  disabled: "Disabled",
  token_saved: "Token saved",
  token_missing: "Token missing",
  polling_short: "polling",
  heartbeat_short: "heartbeat",
  edit: "Edit",
  remove: "Remove",
  printer_selection: "Printer Selection",
  printer: "Printer",
  no_printers: "No printers found",
  refresh: "Refresh",
  endpoint_controls: "Endpoint Controls",
  start_polling_on_launch: "Start polling on launch",
  start_at_login: "Start at login",
  connection_status: "Connection Status",
  heartbeat: "Heartbeat",
  save: "Save",
  start: "Start",
  stop: "Stop",
  recent_jobs: "Recent Jobs",
  no_jobs: "No jobs yet",
  logs_status: "Logs / Status",
  no_logs: "No log output yet",
  loading: "Loading PrintBridge Endpoint…",
  confirm_remove: "Remove {name}? This also removes its stored client token.",
  server_name: "Server Name",
  server_url: "Server URL",
  client_token: "Client Token",
  client_token_hint: "Stored tokens remain hidden. Leave this empty to keep the existing token.",
  token_saved_placeholder: "Token saved (hidden)",
  token_missing_placeholder: "Enter client token",
  show_token: "Show token",
  polling_interval: "Polling Interval",
  heartbeat_interval: "Heartbeat Interval",
  seconds: "seconds",
  test_connection: "Test Connection",
  testing: "Testing…",
  cancel: "Cancel",
  add: "Add Server",
  update: "Save Changes",
  server_required: "Server name and URL are required.",
  server_not_found: "Server not found.",
  save_failed: "Could not save server settings.",
  connection_success: "Connection successful.",
  connection_failed: "Connection failed.",
});
